---
title: "R Notebook"
output: html_notebook
---

```{r warning=FALSE, message=FALSE, error=FALSE}
library(tidyverse)
library(readr)
library(tm)
library(stringr)
```


# Análises descritiva de dados

## Preparando dados das reclamações

```{r warning=FALSE, message=FALSE, error=FALSE}
links_listas_orgaos <- read_csv("../../data/reclamacoes-raw/links-listas-orgaos.csv")
reclamacoes_raw <- read_csv("../../data/reclamacoes-raw/reclamacoes-raw.csv")
experimento_de_avaliacao <- read_csv("../../data/experimento-avaliacao-humana/experimento-de-avaliacao.csv")
```

Olhando rapidamente a estrutura dos dados

```{r warning=FALSE, message=FALSE, error=FALSE}
glimpse(reclamacoes_raw)
```

```{r warning=FALSE, message=FALSE, error=FALSE}
glimpse(links_listas_orgaos)
```

```{r warning=FALSE, message=FALSE, error=FALSE}
glimpse(experimento_de_avaliacao)
```

Calculando tamanho de reclamações e de títulos

```{r warning=FALSE, message=FALSE, error=FALSE}
reclamacoes_raw$tam_titulo = nchar(reclamacoes_raw$titulo)
reclamacoes_raw$tam_reclamacao = nchar(reclamacoes_raw$reclamacao)
```

Calculando quantidade de palavras

```{r warning=FALSE, message=FALSE, error=FALSE}
reclamacoes_raw$n_words = str_count(reclamacoes_raw$reclamacao,'\\w+')
```

Calculando quantidade de palavras em caixa alta

```{r warning=FALSE, message=FALSE, error=FALSE}
reclamacoes_raw$n_upperwords = 0
N_UPPERWORDS_COL_INDEX = grep("^n_upperwords$", colnames(reclamacoes_raw))
RECLAMACAO_COL_INDEX = grep("^reclamacao$", colnames(reclamacoes_raw))

for (i in 1:NROW(reclamacoes_raw)) {
    v = str_replace_all(reclamacoes_raw[i,RECLAMACAO_COL_INDEX], "[^[:alnum:]]", " ")
    reclamacoes_raw[i,N_UPPERWORDS_COL_INDEX] = str_count(v, "\\b[A-Z]{2,}\\b")
}
```

```{r}

reclamacoes_raw$nome_orgao = 0
LINK_COL_INDEX = grep("^link$", colnames(reclamacoes_raw))
ORGAO_COL_INDEX = grep("^nome_orgao$", colnames(reclamacoes_raw))

for (i in 1:NROW(reclamacoes_raw)) {
    link = str_replace_all(reclamacoes_raw[i, LINK_COL_INDEX], "/", "SLICE")
    link = str_replace_all(link, "-", "UNDERLINE")
    link = str_replace_all(link, "[^[:alnum:]]", "&")
    link = str_replace_all(reclamacoes_raw[i, LINK_COL_INDEX], "SLICE", "/")
    reclamacoes_raw[i, ORGAO_COL_INDEX] = link
    #reclamacoes_raw[i, ORGAO_COL_INDEX] = strsplit(reclamacoes_raw$nome_orgao, "/")
}

pega_nome = function(link) {
    v = strsplit(link, "/")
    return(v[[1]][5])
}

reclamacoes_raw$nome_orgao = sapply(reclamacoes_raw$nome_orgao, pega_nome)
```


## Análise dos dados de validação
