---
title: "Analisa sentimentos das reclamações"
output: html_notebook
---


```{r}
pkg = c('tidyverse', 'tidytext', 'here', 'lexiconOT', 'tm')

# Se você não tem esses packages instalados, descomente a seguinte linha:
#install.packages(pkg)
```

```{r warning=FALSE, message=FALSE, error=FALSE}
library(tidyverse)
library(tidytext)
library(here)
library(lexiconPT)
library(tm)
theme_set(theme_bw())
```

```{r warning=FALSE, message=FALSE, error=FALSE}
reclamacoes_raw = read_csv(here("data/reclamacoes-raw/reclamacoes-raw.csv"))

reclamacoes = reclamacoes_raw %>% 
    mutate(id = 1:n())
```

O processo de estimativa será muito baseado em https://sillasgonzaga.github.io/2017-09-23-sensacionalista-pt01/ . 

```{r prepara_sentimento}
data("oplexicon_v3.0")
data("sentiLex_lem_PT02")

op30 <- oplexicon_v3.0
sent <- sentiLex_lem_PT02

glimpse(op30)
```

Precisamos de um dataframe onde cada observação é uma palavra. 

```{r separa}
stopwords = stopwords("pt")

palavra_a_palavra = reclamacoes %>% 
    select(id, reclamacao) %>% 
    unnest_tokens(termo, reclamacao, to_lower = FALSE) %>%
    filter(! termo %in% stopwords) %>%
    count(id, termo) %>%
    mutate(is_lower = termo == tolower(termo)) %>%
    ungroup()

total_words = palavra_a_palavra %>% group_by(id) %>% summarize(total = sum(n))
palavra_a_palavra = left_join(palavra_a_palavra, total_words, by = c("id" = "id"))

palavra_a_palavra = palavra_a_palavra %>%
  bind_tf_idf(termo, id, n)

palavras_com_sentimento = palavra_a_palavra %>% 
    left_join(op30 %>% select(term, op30 = polarity), by = c("termo" = "term")) %>% 
    left_join(sent %>% select(term, sent = polarity), by = c("termo" = "term")) %>%
    mutate(
        op30_tf_idf = ifelse(is_lower, op30 * tf_idf, 2 * op30 * tf_idf),
        sent_tf_idf = ifelse(is_lower, sent * tf_idf, 2 * sent * tf_idf),
        op30 = ifelse(is_lower, op30 * n, op30 * n * 2),
        sent = ifelse(is_lower, sent * n, sent * n * 2)
    )
```


Agora de fato calculamos qual a polaridade acumulada (via somatório) de cada reclamação e salvamos em um csv.

```{r calcula_sentimentos}
sentimentos = palavras_com_sentimento %>% 
    group_by(id) %>%
    summarise(sentimento_op30_tf_idf = sum(op30_tf_idf, na.rm = TRUE),
              sentimento_op30 = sum(op30, na.rm = TRUE),
              palavras_op30 = sum(!is.na(op30)),
              sentimento_sent_tf_idf = sum(sent_tf_idf, na.rm = TRUE), 
              sentimento_sent = sum(sent, na.rm = TRUE), 
              palavras_sent = sum(!is.na(sent)),
              palavras = n())

sentimentos %>% 
    write_csv(here("data/sentimentos/sentimento.csv"))
```

